### ISSUE TITLE
FlopCountAnalysis: ignore modules or modules with specified type

### ISSUE THREAD

**Issue by senysenyseny16** [facebookresearch/fvcore#74]
Hi all,

Is there an option to ignore some specified modules or modules with specified type?
For example,
```python
class MyModule(nn.Module):
    def __init__(self):
        self.m1 = nn.Conv2d(...)
        self.m2 = nn.Conv2d(...)
        ....
        self.mN = nn.Conv2d(...)
```
here I want to ignore for flops calculation all modules embedded in `MyModule`.
I tried to pass `MyModule` with `None`-handler with the help of `set_op_handler`, but `MyModule` is not an operation, this did not work.

Thanks.

**Comment by ericmintun** [comment]
The ability to customize flop counting at the module level instead of the operator level is not currently a feature. This includes excluding specified modules. However, if your goal is to get a flop count for a subset of the network, the flops for all submodules are recorded, and so it should be possible to subtract off unwanted modules from the total, along the lines of 

```python
def flops_excluding_module_type(flops, model, to_exclude):
    flops_subset = flops.total("")
    removed = []
    for n, m in model.named_modules():
        # Avoid double subtracting children of an excluded module
        if any(n.startswith(r) for r in removed):
            continue
        if isinstance(m, to_exclude):
            removed.append(n)
            flops_subset -= flops.total(n)
    return flops_subset
```
where `flops` is a `FlopCountAnalysis` instance and e.g. `to_exclude = MyModule`.
