### ISSUE TITLE
"flop_count" for Detectron2 DeformConv

### ISSUE THREAD

**Issue by bowenc0221** [facebookresearch/fvcore#84]
I'm trying to calculate the flops for Detectron2 Deformable Conv, but I'm having trouble figuring out what should be the `name` of the handler:

```python
def deform_conv_flop_jit(inputs: List[Any], outputs: List[Any]) -> typing.Counter[str]:
    """
    Count flops for deformable convolution.
    """

flops = FlopCountAnalysis(model, data)

handlers = {name: deform_conv_flop_jit}
flops.set_op_handle(**handlers)
```

According to the doc string, the name should be "in the form of ``list(torch._C.Value)``". But I got `TypeError: 'pybind11_type' object is not iterable` when I try to check what's in this list. Could you let me know where I can figure out the name?

**Comment by ppwwyyxx** [comment]
Does the example in https://detectron2.readthedocs.io/en/latest/modules/fvcore.html#fvcore.nn.ActivationCountAnalysis.set_op_handle help?
It means that the arguments of the handler (not of the function `set_op_handle`) has type `List[torch._C.Value]`. The name is just a string, and should be the operator (something like `torchvision::nms`).

However a problem is that deform conv in detectron2 is not registered as a torch operator so it cannot be counted. That's a different issue that belongs to detectron2.

**Comment by bowenc0221** [comment]
Yes, I was trying to follow that example. And do you mean current flop_count implementation does not support any CUDA ops that are not registered as the official torch operator?

Should I open a separate issue in detectron2 for this?

**Comment by ppwwyyxx** [comment]
https://github.com/facebookresearch/fvcore/commit/c17135ab60f9fab2301586f2ff4e00be44a2b50e adds support and shows how autograd function can be counted.

However it's still best to register the ops because that gives the ops a proper and stable name. Currently detectron2 only registers one nms_rotated op: https://github.com/facebookresearch/detectron2/blob/730ccefc7794bd2db0558128c341babdf328e104/detectron2/layers/csrc/vision.cpp#L125-L128 but not others.
